# Generated by Django 4.0.5 on 2022-06-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charachter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('episode', models.CharField(max_length=200)),
            ],
        ),
    ]
